### ISSUE TITLE
The constructor HtmlElementDecorator(WebDriver) is undefined	

### ISSUE THREAD

**Issue by andrew-sumner** [yandex-qatools/htmlelements#105]
The readme says that to use this I should add this code to my pageobject:

    PageFactory.initElements(new HtmlElementDecorator(driver), this);

However that is giving me this error: The constructor HtmlElementDecorator(WebDriver) is undefined	

Any idea what might be wrong?

I'm using ru.yandex.qatools.htmlelements:htmlelements-java:1.15

**Comment by sanjevsunder** [comment]
There is an issue with the readme, someone should change it.

Instead of:
`PageFactory.initElements(new HtmlElementDecorator(driver), this);`
You should do this:
`PageFactory.initElements(new HtmlElementDecorator(new HtmlElementLocatorFactory(driver)), this);`

Reference: http://stackoverflow.com/questions/34806069/incompatible-types-error-in-htmlelementdecoratordriver

**Comment by aik099** [comment]
Could you please send a PR with that change?

**Comment by sanjevsunder** [comment]
@aik099 Here is the PR - https://github.com/yandex-qatools/htmlelements/pull/106

**Comment by ham1** [comment]
Looks like this issue can closed?
